### ISSUE TITLE
Never receive Message Event

### ISSUE THREAD

**Issue by peterbenoit** [lottoinc/cordova-mixpanel#1]
Hi, first of all, thanks for putting this project together!

I'm having some trouble receiving a message. Everything _seems_ to be working, but messages never appear.  The device registers just fine.

I've setup a [demo project](https://github.com/peterbenoit/pn) that I'm hoping you can take a quick look at, maybe I've missed something obvious?

Steps I've done:
1. Created cordova project for iOS and Android 
2. [Automatic Installation](https://github.com/thelinuxkid/PushPlugin#automatic_installation) of PushNotification plugin
3. [Installed cordova-mixpanel plugin](https://github.com/thelinuxkid/cordova-mixpanel)
4. Modified [index2.js](https://github.com/peterbenoit/pn/blob/master/www/js/index2.js) with Mixpanel init code, and senderID
5. Deploy to Android device
6. Send Mixpanel push notification to selected device
   - device is listed and active, so I choose it directly to send a notification to

**Comment by thelinuxkid** [comment]
Sure! So, this plugin needs a forked version of the PushNotification plugin. I will make that more clear in the README. Try using this https://github.com/thelinuxkid/PushPlugin and let me know if it works.

**Comment by peterbenoit** [comment]
Thanks for working with me on this.

Making the change to your version of the PushPlugin helped, but while I get an inline notification while the app has focus, I never receive a notification in the status bar and I never receive a notification if the app doesn't have focus.

I started a new project https://github.com/peterbenoit/mp, here are the steps I took:

forked cordova-mixpanel
forked PushPlugin

cordova create PROJECT
cordova platform add iOS
cordova platform add android
cordova platform add browser

cordova plugin add https://github.com/thelinuxkid/PushPlugin.git
cordova plugin add https://github.com/thelinuxkid/cordova-mixpanel
cordova plugin add cordova-plugin-device

copied PushNotification.js from PushPlugin/www/ to PROJECT/www/js/
added PushNotification.js reference in index.html
updated index.js with senderID and Mixpanel settings
copied mixpanel.js from cordova-mixpanel/www to PROJECT/www/js/
added mixpanel.js reference in index.html
modified mixpanel.js commenting module.exports lines 126,127

cordova run android --device

Mixpanel
Select matched person from "Explore"
"Send a Notification" > Push Notification

**Comment by thelinuxkid** [comment]
Did you follow
https://github.com/thelinuxkid/cordova-mixpanel#push-notifications? I don't
see the messageKey being set. You also don't need to fork either of the
repos nor do you need to copy PushNotification.js or mixpanel.js.

On Tue, Jul 28, 2015 at 7:21 AM, Peter Benoit notifications@github.com
wrote:

> Thanks for working with me on this.
> 
> Making the change to your version of the PushPlugin helped, but while I
> get an inline notification while the app has focus, I never receive a
> notification in the status bar and I never receive a notification if the
> app doesn't have focus.
> 
> I started a new project https://github.com/peterbenoit/mp, here are the
> steps I took:
> 
> forked cordova-mixpanel
> forked PushPlugin
> 
> cordova create PROJECT
> cordova platform add iOS
> cordova platform add android
> cordova platform add browser
> 
> cordova plugin add https://github.com/thelinuxkid/PushPlugin.git
> cordova plugin add https://github.com/thelinuxkid/cordova-mixpanel
> cordova plugin add cordova-plugin-device
> 
> copied PushNotification.js from PushPlugin/www/ to PROJECT/www/js/
> added PushNotification.js reference in index.html
> updated index.js with senderID and Mixpanel settings
> copied mixpanel.js from cordova-mixpanel/www to PROJECT/www/js/
> added mixpanel.js reference in index.html
> modified mixpanel.js commenting module.exports lines 126,127
> 
> cordova run android --device
> 
> Mixpanel
> Select matched person from "Explore"
> "Send a Notification" > Push Notification
> 
> > On Jul 27, 2015, at 4:42 PM, Andres Buritica notifications@github.com
> > wrote:
> > 
> > Sure! So, this plugin needs a forked version of the PushNotification
> > plugin. I will make that more clear in the README. Try using this
> > https://github.com/thelinuxkid/PushPlugin <
> > https://github.com/thelinuxkid/PushPlugin> and let me know if it works.
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/thelinuxkid/cordova-mixpanel/issues/1#issuecomment-125336657
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thelinuxkid/cordova-mixpanel/issues/1#issuecomment-125625083
> .

## 

Andres Buritica
[image: Twitter] http://twitter.com/thelinuxkidd [image: LinkedIn]
http://www.linkedin.com/in/thelinuxkid [image: about.me]
http://about.me/thelinuxkid [image: Blogger]
http://blog.thelinuxkid.com/  https://github.com/thelinuxkid

**Comment by thelinuxkid** [comment]
Is everything working now?

**Comment by peterbenoit** [comment]
Hey! Thanks for checking in. Never did get it working, so I switched to
Pushwoosh instead.

**Comment by thelinuxkid** [comment]
Got it. I will close this then.

On Wednesday, August 12, 2015, Peter Benoit notifications@github.com
wrote:

> Hey! Thanks for checking in. Never did get it working, so I switched to
> Pushwoosh instead.
> On Aug 12, 2015 6:00 PM, "Andres Buritica" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Is everything working now?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/thelinuxkid/cordova-mixpanel/issues/1#issuecomment-130460516
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thelinuxkid/cordova-mixpanel/issues/1#issuecomment-130479174
> .

## 

Andres Buritica
[image: Twitter] http://twitter.com/thelinuxkidd [image: LinkedIn]
http://www.linkedin.com/in/thelinuxkid [image: about.me]
http://about.me/thelinuxkid [image: Blogger]
http://blog.thelinuxkid.com/  https://github.com/thelinuxkid

**Comment by sattarab** [comment]
@peterbenoit I came across the same issue it seems that this issue is related to PushPlugin only creating a notification if a message parameter is send back by gcm. As mixpanel doesn't adhere to this requirement a notification is never really created. You can check this behaviour on this line https://github.com/phonegap-build/PushPlugin/blob/master/src/android/com/plugin/gcm/GCMIntentService.java#L75

**Comment by thelinuxkid** [comment]
Thanks @sattarab. That's right. It is why I created a fork of the Plugin which allows for difference messages keys: https://github.com/thelinuxkid/PushPlugin/blob/master/src/android/com/plugin/gcm/GCMIntentService.java#L74. Unfortunately, the PR hasn't been merged. I will ping them again about it,
