### ISSUE TITLE
Unable to receive background push notifications

### ISSUE THREAD

**Issue by emgeee** [lottoinc/cordova-mixpanel#2]
I have configured a cordova app with the appropriate [fork](https://github.com/thelinuxkid/PushPlugin) of PushPlugin and installed this plugin according to the instructions. When the app is open, I am able to send notifications and receive them in the foreground however when I try to send a notification when the app is either closed or in the background, nothing happens. When I look through the logs with logcat, it doesn't appear that any notifications are being received.

Any help would be appreciated.

**Comment by thelinuxkid** [comment]
@emgeee first I want to make sure you are following https://github.com/thelinuxkid/cordova-mixpanel#push-notifications. Also, please post a snippet of your config.

**Comment by thelinuxkid** [comment]
Any luck with this?

**Comment by emgeee** [comment]
Sorry for the delay on this. I just tried again and was actually able to get it to work. My issue was a combination of not properly setting the GCM `data.mp_message` field as well as not realizing that when mixpanel says "instantaneous" they really mean sometime in the next 30 minutes.
